# Generated by Django 4.1.5 on 2023-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_product_vote_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vote_users',
            field=models.TextField(blank=True, default=''),
        ),
    ]
